version: '3.1'

services:
  # Build the backend container
  backend:
    # Use the Dockerfile in the backend directory
    build: ./backend # path to the Dockerfile
    volumes:
      - ./backend:/usr/src/app # Mount the backend directory to the container
      - /usr/src/app/node_modules # Exclude node_modules from the mount
    # set the port to 3000 (local:container)
    ports:
      - "3000:3000"
    # Set environment variables: connect backend to MongoDB database
    environment:
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=reactproject
      - MONGO_DB_URL=db:27017/react_docker_db # Using the service name of the mongo container
    depends_on:
      - db

  # Build the frontend container
  react-builder:
    # Use the Dockerfile in the frontend directory
    build:
      context: .
      dockerfile: Dockerfile
    # Mount the frontend directory to the container
    volumes:
      - ./build:/app/build

    # Build the nginx container to serve the React app
  nginx:
    image: nginx:latest
    volumes:
    # Mount the build directory and the Nginx configuration to the container
      - ./build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    # Set the port to 80 (default value for Nginx) (local:container)
    ports:
      - 80:80

  # Creating a MongoDB container: creation of the database using MongoDB
  db:
    image: mongo:latest
    # Set environment variables for the database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: reactproject
      MONGO_INITDB_DATABASE: react_docker_db
    # Mount the database data to the container
    volumes:
      - db-data:/data/db
    # Set the port to 27017 (default value for MongoDB)
    ports:
      - 27017:27017

  # Creating a mongo-express container: using mongo-express to manage the database
  mongo-express:
    image: mongo-express
    restart: always
    # Set the port to 8081 (local:container)
    ports:
    - 8081:8081
    environment:
      # Set environment variables for mongo-express
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: reactproject
      ME_CONFIG_MONGODB_SERVER: db  # this should match the service name of your mongo container
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: reactproject

# Create a volume for the database
volumes:
  db-data: